install.packages('udunits2',configure.args='--with-udunits2-include=/usr/include/udunits2/', repos = 'https://ftp.osuosl.org/pub/cran/')"
install.packages('tidyverse', repos = 'https://ftp.osuosl.org/pub/cran/')
install.packages('devtools', repos = 'https://ftp.osuosl.org/pub/cran/')
install.packages('raster', repos = 'https://ftp.osuosl.org/pub/cran/')
install.packages('crawl', repos = 'https://ftp.osuosl.org/pub/cran/')
install.packages('future', repos = 'https://ftp.osuosl.org/pub/cran/')
install.packages('foreach', repos = 'https://ftp.osuosl.org/pub/cran/')
install.packages('doFuture', repose = 'https://ftp.osuosl.org/pub/cran/')
install.packages('furrr', repos = 'https://ftp.osuosl.org/pub/cran/')
